# Generated by Django 5.2.6 on 2025-09-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_education_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='skill_icon'),
        ),
    ]
