# Generated by Django 5.2.6 on 2025-09-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_skill_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='icon',
        ),
        migrations.AddField(
            model_name='skill',
            name='icon_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
