# Generated by Django 5.2.6 on 2025-09-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_skill_icon_skill_icon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume'),
        ),
    ]
