# Generated by Django 5.2.6 on 2025-09-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_introduction_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_img/'),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_img/'),
        ),
    ]
