# Generated by Django 5.2.6 on 2025-09-22 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_introduction_profile_img_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created_at']},
        ),
    ]
