# Generated by Django 5.2.6 on 2025-09-22 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
    ]
